### ISSUE TITLE
Thanks for updating the Plugin - here are some further suggestions.

### ISSUE THREAD

**Issue by HiDTH** [mpaperno/MSFSTouchPortalPlugin#3]
Hi - I am so glad that you are updating the MSFS plugin as there is so much more that can be done through Simconnect.  Pleased also to see that you have already included some items from my wishlist in your recent 0.5.4-mp update.

Below are a number of suggestions - some of which will be easier to implement than others - I have included SimVars and Event IDs where I could find them.  All of them are things I can use to improve my FltSim 2020 page.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

RADIO & NAVIGATION
To be able to pass i.e. Radio Frequencies for COM1, COM2, NAV1, NAV2, ADF, & Transponder directly to the simulator (either live or standby frequency) : Transponder SQAWK Ident.    i.e. Set COM1: 125.60 

COM_RADIO_SET_HZ
COM_STBY_RADIO_SET_HZ
COM1_TRANSMIT_SELECT
COM2_RADIO_SET_HZ
COM2_STBY_RADIO_SET_HZ
COM2_TRANSMIT_SELECT

NAV1_RADIO_SET_HZ
NAV1_STBY_RADIO_SET_HZ
NAV2_RADIO_SET_HZ
NAV1_STBY_RADIO_SET_HZ

XPNDR_SET | Sets transponder code (BCD)
XPNDR_IDENT_TOGGLE

AIRCRAFT INSTRUMENTS
Set pressure (QNH) in either inches of mercury (US system) or hPa (hectopascal European system)

BAROMETRIC | Syncs altimeter setting to sea level pressure, or 29.92 if above 18000 feet | Shared Cockpit
BAROMETRIC_STD_PRESSURE
KOHLSMAN_SET | Sets altimeter setting (Millibars * 16)

I can generate a string value to be passed to the system using an on screen number pad in Touch Portal

SYSTEM
Live value for Active Pause

ENGINE
Engine RPM actual value rather than just %
GENERAL ENG RPM:index

Camera movement functions (i.e. look or move - up, down, left, right) so that keyboard keys do not need to be used

**Comment by mpaperno** [comment]
Hi Denham,

First I'd like to say thanks for your flight sim TP pages, that's pretty much what got me to use this plugin in the first place (they sure look sexy!).  I've hacked up my own version now (of course) but it was a great starting point, and naturally I still keep an original version in TP as a resource.

All good suggestions, thanks, and this is a good place to track them.  There's so many options, it's hard to know which ones are really useful to people.  There's another I think you'll find useful... "ON GROUND" (or something like that) indicating the plane is not flying.  Should simplify some of your button logic :)

I'm finishing up a new version of the plugin which will allow us to send free-form values (frequency, whatever), to make all those "Set" commands work.  It will also allow some basic calculation, so for example you could use the current altitude (via state) for the AP set command, or, say, add 1K feet to it with a button press (custom incr/decr stepping).  I do have to look into how to set the frequency with decimals (since we can only send integers), but there must be a way.

Cheers,
-Max

**Comment by mpaperno** [comment]
All this stuff is available to customize as of v0.7.0 of the plugin. And many of the Sim Vars can now be Set to a value as needed.
