### ISSUE TITLE
MSFS Starter Page import warnings

### ISSUE THREAD

**Issue by SOFTWAREKOCH** [mpaperno/MSFSTouchPortalPlugin#69]
Hi,

i just installed the plugin in MSFS2024 => -All OK
Additional i copied the WASM into my community folder => All OK

When importing the the MFS Start Page, i get a MessageBox telling me 3 pieces are missing ( see below)

Execpt from that 3 messages it seems to work in MSFS 2024 :-)

![error](https://github.com/user-attachments/assets/40197076-2f60-4c51-be81-960e62beec60)

Brgds Dietmar

**Comment by mpaperno** [comment]
Thanks for the report.  Looks like a Touch Portal issue, though I'll check that page to see about the strange spacing in "MSFSTouch Portal Plugin"  (should all be one word or separate words).  

The other two "fsc...." messages are clearly wrong because they're not plugins at all but "Local Values" that should be defined in the TP "Values" tab.  Possibly they're missing and that's what the message is trying to say.  I did see this myself recently when importing a page, so something is wrong there and needs a TP bug report most likely.

Cheers,
-Max

**Comment by mpaperno** [comment]
I checked the page and with the Touch Portal developers and the part of the message that shows the actual plugin name/ID is intentional and is just meant as a reminder.

The other two entries, `fsc.selectedKnob` and `fsc.adjustFactor` are there incorrectly, since they're "Values" (variables) used in and imported with the page. The TP folks will look into that, and the report is appreciated!

Will close this as there is nothing to be done on our side.

Thanks again!
-Max
